import { writeFileSync } from "node:fs";
import { SEED_CHARACTERS, SEED_PLAYERS } from "../lib/seed";

const q = (v: string) => `'${v.replace(/'/g, "''")}'`;
const arr = (a: string[]) => `array[${a.map(q).join(", ")}]::text[]`;

const players = SEED_PLAYERS.map(
  (p) => `(${q(p.id)}, ${q(p.name)}, ${p.is_guest}, ${q(p.status)}, ${p.sort})`,
).join(",\n  ");

const chars = SEED_CHARACTERS.map(
  (c) =>
    `(${q(c.id)}, ${q(c.player_id)}, ${q(c.name)}, ${q(c.description)}, ${q(c.era)}, ${arr(c.adventures)}, ${c.is_main}, ${c.tracked}, ${c.sort}, ${c.hp_max}, ${c.wp_max}, ${c.ar_max})`,
).join(",\n  ");

// Conflict updates skip *_used and *_max: slot maximums are set only when a character is first added,
// after which the GM view owns them, so re-running never undoes usage or GM changes
const sql = `-- Generated by \`npm run seed:sql\` from lib/seed.ts. Safe to re-run: it never resets slot usage or maximums set in the GM view.
insert into players (id, name, is_guest, status, sort) values
  ${players}
on conflict (id) do update set
  name = excluded.name, is_guest = excluded.is_guest, status = excluded.status, sort = excluded.sort;

insert into characters (id, player_id, name, description, era, adventures, is_main, tracked, sort, hp_max, wp_max, ar_max) values
  ${chars}
on conflict (id) do update set
  player_id = excluded.player_id, name = excluded.name, description = excluded.description, era = excluded.era,
  adventures = excluded.adventures, is_main = excluded.is_main, tracked = excluded.tracked, sort = excluded.sort;
`;

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(`Wrote supabase/seed.sql (${SEED_PLAYERS.length} players, ${SEED_CHARACTERS.length} characters)`);
